name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/vllm-cpu-env

jobs:

  build-x86-64-cpu:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push the Docker image for x86_64 CPU
      run: |
        TIMESTAMP="$(date +%s)"
        docker build -f Dockerfile.cpu -t "$IMAGE_NAME:$TIMESTAMP" -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:x86_64" --shm-size=4g .
        docker push "$IMAGE_NAME:$TIMESTAMP"
        docker push "$IMAGE_NAME:latest"
        docker push "$IMAGE_NAME:x86_64"

  build-arm-cpu:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push the Docker image for ARM CPU
      run: |
        TIMESTAMP="$(date +%s)"
        docker build -f Dockerfile.arm -t "$IMAGE_NAME:$TIMESTAMP" -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:arm64" --shm-size=4g .
        docker push "$IMAGE_NAME:$TIMESTAMP"
        docker push "$IMAGE_NAME:latest"
        docker push "$IMAGE_NAME:arm64"
