name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/vllm-cpu-env"

jobs:
  build-multiarch:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      run: |
        docker run --rm --privileged tonistiigi/binfmt --install all

    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login "${REGISTRY}" -u "${{ github.actor }}" --password-stdin

    # Could add `-t "${IMAGE_NAME}:${TIMESTAMP}" \` to keep old images
    - name: Build and push multi-arch Docker image (overwrite latest)
      run: |
        docker buildx build --push \
          --pull \
          --platform "linux/amd64" -f "Dockerfile.cpu" \
          --platform "linux/arm64" -f "Dockerfile.arm" \
          -t "${IMAGE_NAME}:latest" .
